variables:
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'
  repo: 'https://$(username):$(pat)@github.com/curiosity-ai/tesserae.git'
  msg: 'update_demo_$(build.buildId)'

trigger:
- h5-master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  submodules: true
  persistCredentials: true

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  displayName: 'restore nuget'
  inputs:
    restoreSolution: '**/Tesserae.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/Tesserae/Tesserae.csproj'
    workingDirectory: '$(Build.SourcesDirectory)/Tesserae/'
    arguments: '-c $(buildConfiguration) /p:Version=0.0.$(build.buildId)  /p:AllowUnsafeBlocks=True /p:LangVersion=latest'

- task: VSBuild@1
  displayName: 'build tesserae project'
  inputs:
    solution: '$(Build.SourcesDirectory)/Tesserae/Tesserae.csproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: CmdLine@2
  inputs:
    script: 'dir $(Build.SourcesDirectory)\Tesserae\bin\ /S'
    
- task: DotNetCoreCLI@2
  displayName: 'pack Tesserae'
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)/Tesserae/Tesserae.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'
    buildProperties: 'Version="0.0.$(build.buildId)";AllowUnsafeBlocks="True";LangVersion="latest"'
- task: CmdLine@2
  inputs:
    script: 'dir $(Build.SourcesDirectory)\*.nupkg /S'

- task: NuGetCommand@2
  displayName: 'push  Tesserae to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/H5.Tesserae.0.0.$(build.buildId).nupkg' # The package name comes from the PackageID, not project name
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'

# - task: NuGetCommand@2
#   displayName: 'push Tesserae to github'
#   inputs:
#     command: 'push'
#     packagesToPush: '**/Tesserae.0.0.$(build.buildId).nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'nuget-github-packages'