variables:
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'
  repo: 'https://$(username):$(pat)@github.com/curiosity-ai/tesserae.git'
  msg: 'update_demo_$(build.buildId)'

trigger:
- h5-master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  submodules: true
  persistCredentials: true

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.201
    installationPath: $(Agent.ToolsDirectory)/dotnet



- task: NuGetToolInstaller@0

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool update --global h5-compiler'

- task: CmdLine@2
  inputs:
    script: 'dotnet restore $(Build.SourcesDirectory)\Tesserae\Tesserae.csproj'
    workingDirectory: '$(Build.SourcesDirectory)/Tesserae/'

- task: CmdLine@2
  inputs:
    script: 'dotnet build $(Build.SourcesDirectory)\Tesserae\Tesserae.csproj  -c $(buildConfiguration) /p:Version=0.0.$(build.buildId)'
    workingDirectory: '$(Build.SourcesDirectory)/Tesserae/'
    


# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'restore'
#     projects: '$(Build.SourcesDirectory)/Tesserae/Tesserae.csproj'
#     feedsToUse: 'select'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'build'
#     projects: '$(Build.SourcesDirectory)/Tesserae/Tesserae.csproj'
#     workingDirectory: '$(Build.SourcesDirectory)/Tesserae/'
#     arguments: '-c $(buildConfiguration) /p:Version=0.0.$(build.buildId)'
    
- task: CmdLine@2
  inputs:
    script: 'dir $(Build.SourcesDirectory)\Tesserae\bin\ /S'
    
# - task: DotNetCoreCLI@2
#   displayName: 'pack Tesserae'
#   inputs:
#     command: 'pack'
#     packagesToPack: '$(Build.SourcesDirectory)/Tesserae/Tesserae.csproj'
#     configuration: '$(buildConfiguration)'
#     nobuild: true
#     versioningScheme: 'off'
#     buildProperties: 'Version="0.0.$(build.buildId)"'


# - task: CmdLine@2
#   inputs:
#     script: 'dir $(Build.ArtifactStagingDirectory)\*.nupkg /S'

- task: NuGetCommand@2
  displayName: 'push  Tesserae to nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/*/H5.Tesserae.0.0.$(build.buildId).nupkg' # The package name comes from the PackageID, not project name
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'